### ISSUE TITLE
Hello again :) My css file doesn't work with the website.

### ISSUE THREAD

**Issue by anna-pokhilenko** [anna-pokhilenko/stylish-beets#1]
I wrote some css code, but it doesn't appear on the website at all.

@thomasjbradley

**Comment by thomasjbradley** [comment]
The CSS does seem to be working; did you figure it out?

**Comment by anna-pokhilenko** [comment]
Yes! Sorry for that. I will delete the issue.

Thanks a lot!

**Comment by thomasjbradley** [comment]
👍
